Created project using Rails 5.1.4
EtherCorp/b_project pull request #1
Opened 2017-09-28 21:48 UTC by edramire

Project created using the command 
`rails new b_project database=postgresql`

2017-09-28 22:43 UTC, hek23 approved these changes

2017-09-28 22:53 UTC, hek23 requested changes
Change pull request to Develop instead to master

2017-09-28 22:55 UTC, hek23 approved these changes

2017-09-28 23:34 UTC, Ripza approved these changes
Nice!

2017-09-29 13:15 UTC, dochoaj commented
@edramire Los pull request deben ir con una guía de cómo probar lo que se está entregando. Un template correcto sería:

# [Título de lo que se hizo]

Descripción, blah blah blah

## ¿Cómo probar?

Guía para tu equipo respecto a como probar el PR

2017-09-29 13:20 UTC, dochoaj requested changes
Dejé comentarios en su PR

2017-09-29 13:20 UTC, dochoaj commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Este archivo debe sacarse del versionamiento, ya que todos tenemos ambientes con user y pass distintos. Lo que hay que hacer es versionar un config/database.yml.default y en las instrucciones de como hacer funcionar el proyecto (generalmente en el README) explicar que hay que copiar el archivo y cambiarle el nombre a database.yml.

En resumen:

- Elimina este archivo del versionamiento
- Agregalo al .gitignore
- Agrega config/database.yml.default
- Agrega la instrucción en el README

Esto mismo hay que aplicarlo con todos los archivos de configuración. Esto se puede evitar al dockerizar los ambientes (pero no estamos ahí todavía)

2017-09-29 16:29 UTC, edramire commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Entiendo. ¿El readme en español, o con el tema del inglés sólo se refiere sólo al código?
En la wiki había dejado algunos comentarios (sobre la instalación del ambiente más que nada), pero lo haré más completo.
Gracias por las aclaraciones

2017-09-29 16:35 UTC, hek23 commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Yo creo que en inglés, para seguir la linea del proyecto y de todo lo que hemos estado haciendo.

2017-09-29 16:55 UTC, edramire commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Y los comentarios también?

Eliminaré los archivos
* /config/cable.yml
* /config/database.yml
* /config/secrets.yml

Que son los que he encontrado como importantes de sacar por temas de configuración y claves secretas.

2017-09-29 16:56 UTC, dochoaj commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
@edramire En inglés solo el código y sus presentaciones :)

2017-09-29 16:56 UTC, dochoaj commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
Y las mías

2017-09-29 16:57 UTC, dochoaj commented on config/database.yml
> +# PostgreSQL. Versions 9.1 and up are supported.
1. Todo lo que esté en algun archivo del repo en inglés.
2. Los PR y los comentarios de los PR pueden ser en español

2017-10-01 01:39 UTC, edramire commented
Realizados los cambios solicitados (avisé vía slack también).
@dochoaj @hek23 @Ripza

2017-10-03 15:54 UTC, dochoaj approved these changes

2017-10-03 16:06 UTC, merged